name = "SimpleGA"
uuid = "6f159fe9-4850-48a0-97c4-7cf487b3e6ea"
authors = ["Monumo Ltd.", "Tom Gillam <tpgillam@googlemail.com>"]
version = "0.2.0"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AutoHashEquals = "1, 2"
SparseArrays = "1"
StaticArrays = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
